version: "3"

services:
  vite-app:
    build: 
      context: .
      dockerfile: dockerfile

    container_name: frontend-econ
    tmpfs: /tmp
    ports:
      - "80:3000"
    volumes:
      - ./:/app
    command: ["npm", "run", "dev"]
