version: "3"

services:
  vite-app:
    build: 
      context: .
      dockerfile: dockerfile

    container_name: frontend-econ
    ports:
      - "80:3000"
    volumes:
      - ./:/app
    command: >
      sh -c "npm install && npm run dev"
